// flow-typed signature: 6aee6728de0a38d8a2442d424bf49435
// flow-typed version: <<STUB>>/preact-async-route_v^2.1.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-async-route'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-async-route' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-async-route/dist/index' {
  declare module.exports: any;
}

declare module 'preact-async-route/dist/index.min' {
  declare module.exports: any;
}

declare module 'preact-async-route/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-async-route/dist/index.js' {
  declare module.exports: $Exports<'preact-async-route/dist/index'>;
}
declare module 'preact-async-route/dist/index.min.js' {
  declare module.exports: $Exports<'preact-async-route/dist/index.min'>;
}
declare module 'preact-async-route/src/index.js' {
  declare module.exports: $Exports<'preact-async-route/src/index'>;
}
