// flow-typed signature: dac2e471b73fba43e916d0eb0f38c8e6
// flow-typed version: <<STUB>>/preact-cli-plugin-flow_v^0.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-cli-plugin-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-cli-plugin-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-cli-plugin-flow/bin/index' {
  declare module.exports: any;
}

declare module 'preact-cli-plugin-flow/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-cli-plugin-flow/bin/index.js' {
  declare module.exports: $Exports<'preact-cli-plugin-flow/bin/index'>;
}
declare module 'preact-cli-plugin-flow/src/index.js' {
  declare module.exports: $Exports<'preact-cli-plugin-flow/src/index'>;
}
